# Generated by Django 5.2 on 2025-07-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_marca_alter_producto_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
