# Generated by Django 5.2 on 2025-07-14 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_categoria_subcategoria_subcategoria'),
        ('store', '0003_marca_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_subcategoria', to='category.subcategoria'),
        ),
    ]
