# Generated by Django 5.2 on 2025-09-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_producto_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_efectivo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
