# Generated by Django 5.2.1 on 2025-07-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='ciudad_envio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='cp_envio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='direccion_envio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='tipo_entrega',
            field=models.CharField(choices=[('andreani', 'Envío por Andreani'), ('retiro', 'Retiro en local')], default='andreani', max_length=20),
        ),
    ]
