# Generated by Django 5.2.1 on 2025-07-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orden_ciudad_envio_orden_cp_envio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='numero_orden',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
