# Generated by Django 5.2.1 on 2025-07-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orden_numero_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='numero_orden',
            field=models.CharField(max_length=20),
        ),
    ]
