# Generated by Django 5.2 on 2025-09-18 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orden_numero_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='impuesto',
        ),
    ]
