# Generated by Django 5.2 on 2025-11-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_orden_impuesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandaEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia_hasta', models.FloatField(help_text='La distancia máxima en kilómetros para aplicar este costo.', verbose_name='Distancia máxima (km)')),
                ('costo', models.FloatField(verbose_name='Costo de envío ($)')),
            ],
            options={
                'verbose_name': 'Banda de envío',
                'verbose_name_plural': 'Bandas de envío',
                'ordering': ['distancia_hasta'],
            },
        ),
    ]
